mglaman/drupal-check

README.md, composer.json, composer.lock, drupal-check
=> Mark the requirement of PHP > 7.1

README.md
Thanks, @mglaman - a great tool!
=> Add chmod +x to installation instructions.

README.md
This will always grab the latest PHAR when installing it manually.
=> Update ReadMe to get lastest PHAR

src/Command/CheckCommand.php
=> Update --help format option description

.circleci/config.yml, composer.json, composer.lock
=> Match PHPStan's symfony/console constraints

.circleci/config.yml, composer.lock
=> Add steps for drupal/drupal and drupal-project

.circleci/config.yml
=> Resolve version constraints on symfony/console

.circleci/config.yml
=> Add a test flow for specific contrib

box.json
=> Box recommendations for compile

.circleci/config.yml, composer.lock, src/Command/CheckCommand.php, src/DrupalCheckErrorHandler.php, tests/fixtures/contained_not_initialized/contained_not_initialized.info.yml, tests/fixtures/contained_not_initialized/contained_not_initialized.install, tests/fixtures/contained_not_initialized/contained_not_initialized.module
=> Catch contained_not_initialized and report

.circleci/config.yml
=> Fix for global require tests

.circleci/config.yml, composer.json, composer.lock, phpstan/phpstan_deprecation_rules.php, phpstan/phpstan_drupal_extension.php
Provides an immediate fix for https://github.com/mglaman/drupal-check/issues/78
=> Ensure vendor dir is removed for global install.

.circleci/config.yml
=> Test drupal-check as a project dependency

composer.json, composer.lock, src/Command/CheckCommand.php
Fixes #92  
Fixes #93
Fixes #95
=> Use PHPStan ^0.11.9

README.md, src/Command/CheckCommand.php
Closes #97 
Tested local/global and PHAR installation in the same Docker container that I discovered the bug.
=> Introduce new --drupal-root option

src/Command/CheckCommand.php
=> Adds memory-limit option

README.md
Fixes https://github.com/mglaman/drupal-check/issues/148.
See also https://github.com/mglaman/drupal-check/pull/127.
=> update php requirement in readme

src/Command/CheckCommand.php
=> #154 Pass the "--no-progress" option to phpstan.

composer.json, composer.lock
=> fix compatibility with composer/package-versions-deprecated

src/Command/CheckCommand.php
=> pass memory limit to phpstan

src/Command/CheckCommand.php
Implements the fix by @Chi-teck as a PR: https://github.com/mglaman/drupal-check/issues/137#issuecomment-617091907
=> #137 - Allow redirect output to a file.

.circleci/config.yml, .travis.yml, box.json, stub.php
=> Remove building and usage of the Phar

src/Command/CheckCommand.php
=> Exclude node_modules from analysis

appveyor.yml, src/Command/CheckCommand.php
Relates #180﻿. Doesn't fix 180, but helps us get closer to testing and fixes _some_ problems.
=> Add AppVeyor build configuration for testing

src/Command/CheckCommand.php
Fixes #180, thanks to @DanChadwick
=> Properly add the PHP call in Windows

composer.json, composer.lock
This update resolve this error
Internal error: PHPUnit\Framework\TestCase is not an interface Run PHPStan with --debug option and post the stack trace to: https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
=> TestCase is not an interface

.github/workflows/php.yml, README.md, composer.json, composer.lock, phpstan.neon
Updates workflow for testing with Drupal build artifact﻿
=> Add Github Actions replacing TravisCI

.github/workflows/php.yml, composer.json, composer.lock, drupal-check, src/Command/CheckCommand.php
Adds testing pipeline for contrib to check on #204
=> Add test for config_update and fix missing dependency

.circleci/config.yml, .github/workflows/php.yml, composer.json, composer.lock, src/Command/CheckCommand.php
=> Fix build and deprecated usages of excludes_analyse

composer.json, composer.lock
=> Add "jangregor/phpstan-prophecy" dependency
